[package]
name = "testing"
version = "0.1.0"
edition = "2024"

[dependencies]
crux = { workspace = true, features = [
	"logging",
	"logging-panic-handler",
	"global-os-allocator",
] }
crux-macros.workspace = true

[build-dependencies.crux-build]
workspace = true
features = ["bin"]
