# Runs unit tests.

name: Tests
on: [push, workflow_dispatch]
jobs:
  Documentation-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust Nightly
        run: rustup install
      - name: Cargo Doc
        run: ./bin/doctests.sh

  Linux-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust Nightly
        run: rustup install
      - name: Cargo Test
        run: cargo test
  # macOS-Tests:
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Install Rust Nightly
  #       run: rustup install
  #     - name: Cargo Test
  #       run: cargo test
  # Windows-Tests:
  #   runs-on: windows-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Install Rust Nightly
  #       run: rustup install
  #     - name: Cargo Test
  #       run: cargo test
  Macro-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust Nightly
        run: rustup install
      - name: Cargo Test
        run: ./bin/macro-tests.sh
