# Runs unit tests.

name: Tests
on: [push, workflow_dispatch]
jobs:
  Documentation-Tests:
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: -D warnings
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust Nightly
        run: rustup install
      - name: Cargo Doc
        run: cargo doc --document-private-items

  Linux-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust Nightly
        run: rustup install
      - name: Cargo Test
        run: cargo test
  macOS-Tests:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust Nightly
        run: rustup install
      - name: Cargo Test
        run: cargo test
  Windows-Tests:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust Nightly
        run: rustup install
      - name: Cargo Test
        run: cargo test
  Macro-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Rust Nightly
        run: rustup install
      - name: Cargo Test
        run: cargo test -p crux-macros -p crux-macros-impl -p crux-rust-ast
